from pathlib import Path
from html import escape
R=Path(__file__).parent
ROUTES={"renovatie-plannen":["huis-renoveren","renovatie-volgorde","renovatiefasen","complete-renovatie","renovatiekosten","renovatie-budget","renovatievergunning","subsidies-renovatie","rendement-renovatie"],"renovatieprojecten":["badkamer-renovatie","keuken-renovatie","aanbouw","fundering","ramen-en-glas"],"verduurzamen":["isolatie","isolatie/dakisolatie","isolatie/vloerisolatie","isolatie/gevelisolatie","zonnepanelen","warmtepomp","cv-ketel","ventilatie","dubbel-glas","energie-besparen"],"problemen-oplossen":["vochtproblemen","opstijgend-vocht","vocht-in-muren","funderingsproblemen"],"vakman-en-offertes":["vakman-kiezen","aannemer-kiezen","offertes-vergelijken","offerte-controleren","zelf-doen-of-uitbesteden"],"doe-het-zelf":[]}
LABEL={"renovatie-plannen":"Renovatie plannen","renovatieprojecten":"Renovatieprojecten","verduurzamen":"Verduurzamen","problemen-oplossen":"Problemen oplossen","vakman-en-offertes":"Vakman & offertes","doe-het-zelf":"Doe het zelf"}
def name(s):return LABEL.get(s,s.replace('-',' ').capitalize())
def page(route):
 p=route.split('/'); title=name(p[-1]); trail=['<a href="/">Home</a>']; path=''
 for x in p[:-1]: path+=f'/{x}';trail.append(f'<a href="{path}/">{escape(name(x))}</a>')
 trail.append(escape(title)); bread=' / '.join(trail)
 return f'''<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Thuisrenovatie Gids</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/css/style.css"><script src="/js/site.js" defer></script></head><body><header class="site-header"><div class="utility"><div class="container utility-inner"><span>Onafhankelijke renovatiekeuzes</span><a href="/vakman-en-offertes/offertes-vergelijken/">Zo werkt vergelijken ↗</a></div></div><nav class="container nav"><a class="brand" href="/"><span class="brand-mark"><i></i></span><span>Thuisrenovatie<small>Gids</small></span></a><button class="menu-toggle" aria-expanded="false"><span></span><span></span><span></span><em>Menu</em></button><div class="nav-links"><a href="/renovatie-plannen/">Renovatie plannen</a><a href="/renovatieprojecten/">Projecten</a><a href="/verduurzamen/">Verduurzamen</a><a href="/problemen-oplossen/">Problemen oplossen</a><a href="/vakman-en-offertes/">Vakman vinden</a></div><a class="button small" href="/vakman-en-offertes/offertes-vergelijken/">Vergelijk vakmensen ↗</a></nav></header><main class="empty"><section class="page-head"><div class="container"><div class="breadcrumbs">{bread}</div><h1>{escape(title)}</h1></div></section><section class="blank" aria-label="Lege contentruimte"><div class="container"><div class="skeleton"><div><i></i><i></i><i></i><b></b></div><aside><i></i><i></i><b></b></aside></div></div></section></main><footer class="footer"><div class="container footer-grid"><a class="brand footer-brand" href="/"><span class="brand-mark"><i></i></span><span>Thuisrenovatie<small>Gids</small></span></a><div><h4>Plannen</h4><a href="/renovatie-plannen/">Renovatie plannen</a><a href="/renovatieprojecten/">Renovatieprojecten</a></div><div><h4>Verbeteren</h4><a href="/verduurzamen/">Verduurzamen</a><a href="/problemen-oplossen/">Problemen oplossen</a></div><div><h4>Uitvoeren</h4><a href="/vakman-en-offertes/">Vakman & offertes</a><a href="/doe-het-zelf/">Doe het zelf</a></div></div><div class="container bottom">© 2026 Thuisrenovatie Gids <span>Onafhankelijk beslissen. Beter renoveren.</span></div></footer></body></html>'''
for cat,kids in ROUTES.items():
 for route in [cat]+[f'{cat}/{x}' for x in kids]:
  dest=R/route/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(page(route),encoding='utf-8')
print('Generated',sum(1+len(x) for x in ROUTES.values()),'empty routes')
